/*
 * Calc API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import java.math.BigDecimal;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addArg1Arg2GetTest() throws ApiException {
        BigDecimal arg1 = null;
        BigDecimal arg2 = null;
        BigDecimal response = api.addArg1Arg2Get(arg1, arg2);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void divideArg1Arg2GetTest() throws ApiException {
        BigDecimal arg1 = null;
        BigDecimal arg2 = null;
        BigDecimal response = api.divideArg1Arg2Get(arg1, arg2);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void multiplyArg1Arg2GetTest() throws ApiException {
        BigDecimal arg1 = null;
        BigDecimal arg2 = null;
        BigDecimal response = api.multiplyArg1Arg2Get(arg1, arg2);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void substractArg1Arg2GetTest() throws ApiException {
        BigDecimal arg1 = null;
        BigDecimal arg2 = null;
        BigDecimal response = api.substractArg1Arg2Get(arg1, arg2);

        // TODO: test validations
    }
}
